### ISSUE TITLE
Update time- and voltage-scaling

### ISSUE THREAD

**Issue by t-siedenburg** [bjonnh/owon-sds7102-protocol#5]
Dear authors,

if you are interested, then I would have an update to parse.c 
to get correctly scaled times in s and offset corrected voltages in V
for an OWON SDS-7102 into the output.csv file.

Thanks for your work - it helped a lot
and best regards

  Thorsten Siedenburg
  I.Phys.Inst,  RWTH Aachen

**Comment by mupuf** [comment]
Sure, please send a pull request :)

And glad to hear we helped you!
